#!/usr/bin/env ruby
require '.git/vendor/gitbox/gitbox.rb'

# Initialize Gitbox
gitbox = GitBox.new

# Get task list...
if (gitbox.tasklist.empty?)
  until !gitbox.tasklist.empty?
    gitbox.choose_task_list
  end
end

# Get task
until !gitbox.task.empty?
  gitbox.task = gitbox.choose_task
end

# Get status
until !gitbox.status.empty?
  gitbox.choose_status
end

# Get users
gitbox.choose_user
until !gitbox.user.empty?
  gitbox.choose_user
end

# Get Commit Message
gitbox.get_message

# Call Teambox
result = false
until (result and "#{result.code}" == "201")
  result = gitbox.update_status
  if(!result or !result.code)
    puts "  a critical error occured, aborting"
    exit 1
  end
  
  case "#{result.code}"
    when "401"
      puts "  ERROR 401: authentification failed, please reenter your password"
      gitbox.require_password
    when "201"
      puts "* Teambox status successfully set"
    else
      puts "  ERROR #{result.code}, aborting"
      exit 1
  end
end